# Generated by Django 6.0.5 on 2026-05-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acordo', '0001_initial'),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(db_index=True, verbose_name='Competência')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CARTAO', 'Cartão')], max_length=10, null=True, verbose_name='Forma de Pagamento')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa (R$)')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('acordo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas', to='acordo.acordo', verbose_name='Acordo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='unidade.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'db_table': 'cobrancas',
                'ordering': ['-data_vencimento'],
                'indexes': [models.Index(fields=['unidade', 'status'], name='cobrancas_unidade_158702_idx'), models.Index(fields=['data_vencimento', 'status'], name='cobrancas_data_ve_2e036b_idx'), models.Index(fields=['competencia'], name='cobrancas_compete_753c28_idx')],
            },
        ),
    ]
