# Generated by Django 6.0.5 on 2026-05-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(max_length=10, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(max_length=10, verbose_name='Status Novo')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Alteração')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Usuário')),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='cobranca.cobranca', verbose_name='Cobrança')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'db_table': 'historico_status',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
