# Generated by Django 5.2.1 on 2026-05-28 13:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("condominio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoMulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentual_multa",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.02"),
                        help_text="Ex: 0.02 para 2%",
                        max_digits=5,
                        verbose_name="Porcentual de Multa",
                    ),
                ),
                (
                    "percentual_juros_dia",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.00033"),
                        help_text="Ex: 0.00033 para 0,033 ao dia",
                        max_digits=7,
                        verbose_name="Percentual de Juros por Dia",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "condominio",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracao_multa",
                        to="condominio.condominio",
                        verbose_name="Condominio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Multa",
                "verbose_name_plural": "Configurações de Multa",
                "db_table": "configuracoes_multa",
            },
        ),
    ]
