# Generated by Django 6.0.5 on 2026-05-22 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condominio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('bloco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bloco')),
                ('status', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('VAGO', 'Vago')], db_index=True, default='VAGO', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominio.condominio', verbose_name='Condomínio')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidades',
                'ordering': ['condominio', 'bloco', 'numero'],
                'indexes': [models.Index(fields=['condominio', 'status'], name='unidades_condomi_9e5f65_idx')],
                'constraints': [models.UniqueConstraint(fields=('condominio', 'bloco', 'numero'), name='unique_unidade_por_condominio')],
            },
        ),
    ]
