# Generated by Django 6.0.5 on 2026-05-22 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('numero_parcelas', models.PositiveIntegerField(verbose_name='Número de Parcelas')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado')], db_index=True, default='ATIVO', max_length=10, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='unidade.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Acordo',
                'verbose_name_plural': 'Acordos',
                'db_table': 'acordos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AcordoParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='acordo.acordo', verbose_name='Acordo')),
            ],
            options={
                'verbose_name': 'Parcela do Acordo',
                'verbose_name_plural': 'Parcelas do Acordo',
                'db_table': 'acordo_parcelas',
                'ordering': ['acordo', 'numero_parcela'],
            },
        ),
        migrations.AddIndex(
            model_name='acordo',
            index=models.Index(fields=['unidade', 'status'], name='acordos_unidade_84ef66_idx'),
        ),
        migrations.AddConstraint(
            model_name='acordoparcela',
            constraint=models.UniqueConstraint(fields=('acordo', 'numero_parcela'), name='unique_parcela_por_acordo'),
        ),
    ]
